name: App check and Deploy

on:
  pull_request:
    branches: ['master']
  workflow_dispatch:
  push:
    branches:
      - master # Деплой будет происходить при пуше в master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
